stages:
- stage: DeployDev
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployToDev
    displayName: Deploy Dev
    # creates an environment if it doesn't exist
    environment: 'sweetspot-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: Setup pulumi
            inputs:
              targetType: inline
              script: |
                curl -fsSL https://get.pulumi.com | bash
                export PATH=$PATH:$HOME/.pulumi/bin
                echo "##vso[task.setvariable variable=path]$PATH"
                pulumi login
            env:
              PULUMI_ACCESS_TOKEN: $(pulumi.access.token)            
          - task: Bash@3
            displayName: Deploy dev
            inputs:
              targetType: inline
              script: |
                pulumi stack select dev
                pulumi up -y
